services:
  stevenyambosfrapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ".env"
    volumes:
      - .:/app
      - ~/.aspnet/https:/https:ro
