services:
  stevenyambosfrapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - ".env"
    volumes:
      # - .:/App
      - ~/.aspnet/https:/https:ro
